/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShoppingListItemResponse {
    id: bigint;
    name: string;
    completed: boolean;
    amount: bigint;
}
export interface SortOrder {
    asc: boolean;
}
export interface ShoppingListResponse {
    id: bigint;
    name: string;
    items: Array<ShoppingListItemResponse>;
}
export interface ShoppingListItem {
    id: bigint;
    completed: boolean;
    amount: bigint;
}
export interface ListItemPaginatedResponse {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<ListItem>;
}
export interface ListItemPaginationRequest {
    sortOrder: SortOrder;
    page: bigint;
    pageSize: bigint;
    search?: string;
}
export interface ListItem {
    id: bigint;
    name: string;
}
export interface ShoppingList {
    id: bigint;
    name: string;
    items: Array<ShoppingListItem>;
}
export interface backendInterface {
    addItemsToShoppingList(listId: bigint, shoppingListItems: Array<ShoppingListItem>): Promise<ShoppingListResponse>;
    addListItem(name: string): Promise<ListItem>;
    addShoppingList(name: string): Promise<Array<ShoppingListResponse>>;
    cloneShoppingList(listId: bigint, newName: string): Promise<ShoppingList>;
    completeItems(listId: bigint, itemIds: Array<bigint>): Promise<ShoppingList>;
    deleteShoppingLists(listIds: Array<bigint>): Promise<Array<ShoppingListResponse>>;
    editItemsInShoppingList(listId: bigint, items: Array<ShoppingListItem>): Promise<ShoppingListResponse>;
    getListItemsPaginated(paginationRequest: ListItemPaginationRequest): Promise<ListItemPaginatedResponse>;
    getShoppingList(listId: bigint): Promise<ShoppingListResponse>;
    getShoppingLists(): Promise<Array<ShoppingListResponse>>;
    init(items: Array<string>): Promise<void>;
    isInited(): Promise<boolean>;
    removeItemFromShoppingList(listId: bigint, itemId: bigint): Promise<void>;
}
import type { ListItemPaginationRequest as _ListItemPaginationRequest, SortOrder as _SortOrder } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addItemsToShoppingList(arg0: bigint, arg1: Array<ShoppingListItem>): Promise<ShoppingListResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addItemsToShoppingList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItemsToShoppingList(arg0, arg1);
            return result;
        }
    }
    async addListItem(arg0: string): Promise<ListItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addListItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListItem(arg0);
            return result;
        }
    }
    async addShoppingList(arg0: string): Promise<Array<ShoppingListResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.addShoppingList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShoppingList(arg0);
            return result;
        }
    }
    async cloneShoppingList(arg0: bigint, arg1: string): Promise<ShoppingList> {
        if (this.processError) {
            try {
                const result = await this.actor.cloneShoppingList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cloneShoppingList(arg0, arg1);
            return result;
        }
    }
    async completeItems(arg0: bigint, arg1: Array<bigint>): Promise<ShoppingList> {
        if (this.processError) {
            try {
                const result = await this.actor.completeItems(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeItems(arg0, arg1);
            return result;
        }
    }
    async deleteShoppingLists(arg0: Array<bigint>): Promise<Array<ShoppingListResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShoppingLists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShoppingLists(arg0);
            return result;
        }
    }
    async editItemsInShoppingList(arg0: bigint, arg1: Array<ShoppingListItem>): Promise<ShoppingListResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.editItemsInShoppingList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editItemsInShoppingList(arg0, arg1);
            return result;
        }
    }
    async getListItemsPaginated(arg0: ListItemPaginationRequest): Promise<ListItemPaginatedResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getListItemsPaginated(to_candid_ListItemPaginationRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListItemsPaginated(to_candid_ListItemPaginationRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getShoppingList(arg0: bigint): Promise<ShoppingListResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingList(arg0);
            return result;
        }
    }
    async getShoppingLists(): Promise<Array<ShoppingListResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingLists();
            return result;
        }
    }
    async init(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init(arg0);
            return result;
        }
    }
    async isInited(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInited();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInited();
            return result;
        }
    }
    async removeItemFromShoppingList(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeItemFromShoppingList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeItemFromShoppingList(arg0, arg1);
            return result;
        }
    }
}
function to_candid_ListItemPaginationRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListItemPaginationRequest): _ListItemPaginationRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortOrder: SortOrder;
    page: bigint;
    pageSize: bigint;
    search?: string;
}): {
    sortOrder: _SortOrder;
    page: bigint;
    pageSize: bigint;
    search: [] | [string];
} {
    return {
        sortOrder: value.sortOrder,
        page: value.page,
        pageSize: value.pageSize,
        search: value.search ? candid_some(value.search) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
