/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShoppingListItem = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const ShoppingListItemResponse = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const ShoppingListResponse = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'items' : IDL.Vec(ShoppingListItemResponse),
});
export const ListItem = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const ShoppingList = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'items' : IDL.Vec(ShoppingListItem),
});
export const SortOrder = IDL.Record({ 'asc' : IDL.Bool });
export const ListItemPaginationRequest = IDL.Record({
  'sortOrder' : SortOrder,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'search' : IDL.Opt(IDL.Text),
});
export const ListItemPaginatedResponse = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(ListItem),
});

export const idlService = IDL.Service({
  'addItemsToShoppingList' : IDL.Func(
      [IDL.Nat, IDL.Vec(ShoppingListItem)],
      [ShoppingListResponse],
      [],
    ),
  'addListItem' : IDL.Func([IDL.Text], [ListItem], []),
  'addShoppingList' : IDL.Func([IDL.Text], [IDL.Vec(ShoppingListResponse)], []),
  'cloneShoppingList' : IDL.Func([IDL.Nat, IDL.Text], [ShoppingList], []),
  'completeItems' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [ShoppingList], []),
  'deleteShoppingLists' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(ShoppingListResponse)],
      [],
    ),
  'editItemsInShoppingList' : IDL.Func(
      [IDL.Nat, IDL.Vec(ShoppingListItem)],
      [ShoppingListResponse],
      [],
    ),
  'getListItemsPaginated' : IDL.Func(
      [ListItemPaginationRequest],
      [ListItemPaginatedResponse],
      [],
    ),
  'getShoppingList' : IDL.Func([IDL.Nat], [ShoppingListResponse], []),
  'getShoppingLists' : IDL.Func([], [IDL.Vec(ShoppingListResponse)], []),
  'init' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'isInited' : IDL.Func([], [IDL.Bool], []),
  'removeItemFromShoppingList' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShoppingListItem = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const ShoppingListItemResponse = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const ShoppingListResponse = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'items' : IDL.Vec(ShoppingListItemResponse),
  });
  const ListItem = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const ShoppingList = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'items' : IDL.Vec(ShoppingListItem),
  });
  const SortOrder = IDL.Record({ 'asc' : IDL.Bool });
  const ListItemPaginationRequest = IDL.Record({
    'sortOrder' : SortOrder,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'search' : IDL.Opt(IDL.Text),
  });
  const ListItemPaginatedResponse = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(ListItem),
  });
  
  return IDL.Service({
    'addItemsToShoppingList' : IDL.Func(
        [IDL.Nat, IDL.Vec(ShoppingListItem)],
        [ShoppingListResponse],
        [],
      ),
    'addListItem' : IDL.Func([IDL.Text], [ListItem], []),
    'addShoppingList' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShoppingListResponse)],
        [],
      ),
    'cloneShoppingList' : IDL.Func([IDL.Nat, IDL.Text], [ShoppingList], []),
    'completeItems' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [ShoppingList], []),
    'deleteShoppingLists' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(ShoppingListResponse)],
        [],
      ),
    'editItemsInShoppingList' : IDL.Func(
        [IDL.Nat, IDL.Vec(ShoppingListItem)],
        [ShoppingListResponse],
        [],
      ),
    'getListItemsPaginated' : IDL.Func(
        [ListItemPaginationRequest],
        [ListItemPaginatedResponse],
        [],
      ),
    'getShoppingList' : IDL.Func([IDL.Nat], [ShoppingListResponse], []),
    'getShoppingLists' : IDL.Func([], [IDL.Vec(ShoppingListResponse)], []),
    'init' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'isInited' : IDL.Func([], [IDL.Bool], []),
    'removeItemFromShoppingList' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };