/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ListItem { 'id' : bigint, 'name' : string }
export interface ListItemPaginatedResponse {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<ListItem>,
}
export interface ListItemPaginationRequest {
  'sortOrder' : SortOrder,
  'page' : bigint,
  'pageSize' : bigint,
  'search' : [] | [string],
}
export interface ShoppingList {
  'id' : bigint,
  'name' : string,
  'items' : Array<ShoppingListItem>,
}
export interface ShoppingListItem {
  'id' : bigint,
  'completed' : boolean,
  'amount' : bigint,
}
export interface ShoppingListItemResponse {
  'id' : bigint,
  'name' : string,
  'completed' : boolean,
  'amount' : bigint,
}
export interface ShoppingListResponse {
  'id' : bigint,
  'name' : string,
  'items' : Array<ShoppingListItemResponse>,
}
export interface SortOrder { 'asc' : boolean }
export interface _SERVICE {
  'addItemsToShoppingList' : ActorMethod<
    [bigint, Array<ShoppingListItem>],
    ShoppingListResponse
  >,
  'addListItem' : ActorMethod<[string], ListItem>,
  'addShoppingList' : ActorMethod<[string], Array<ShoppingListResponse>>,
  'cloneShoppingList' : ActorMethod<[bigint, string], ShoppingList>,
  'completeItems' : ActorMethod<[bigint, Array<bigint>], ShoppingList>,
  'deleteShoppingLists' : ActorMethod<
    [Array<bigint>],
    Array<ShoppingListResponse>
  >,
  'editItemsInShoppingList' : ActorMethod<
    [bigint, Array<ShoppingListItem>],
    ShoppingListResponse
  >,
  'getListItemsPaginated' : ActorMethod<
    [ListItemPaginationRequest],
    ListItemPaginatedResponse
  >,
  'getShoppingList' : ActorMethod<[bigint], ShoppingListResponse>,
  'getShoppingLists' : ActorMethod<[], Array<ShoppingListResponse>>,
  'init' : ActorMethod<[Array<string>], undefined>,
  'isInited' : ActorMethod<[], boolean>,
  'removeItemFromShoppingList' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];